server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  cache:
    type: hazelcast
    cache-names: "balance"
  main:
    banner-mode: off


logging:
  file:
    name: log
  level:
    com.example.test_task_server.controller.BalanceController: INFO
    org.springframework: info
    org.hibernate: info
    root: info




